### ISSUE TITLE
Add API Gateway endpoints

### ISSUE THREAD

**Issue by mhart** [lambci/lambci#1]
This is a rather large topic, but there are few things here that this would enable:
1. Authenticated build logs / badges
2. Admin interface
   1. view builds
   2. rebuild
   3. update config
3. Web hooks (for GitHub and other sources like BitBucket, etc)
4. REST API that other clients (like a CLI client) could talk to

**Comment by Jonnx** [comment]
+1 for the rebuild functionality

**Comment by mhart** [comment]
@Jonnx you can rebuild using the command line: https://github.com/lambci/cli#lambci-rebuild

**Comment by mhart** [comment]
This is done as of 0.10.0 (no admin interface or anything though)
