### ISSUE TITLE
Add PHP support

### ISSUE THREAD

**Issue by mhart** [lambci/lambci#10]
It should (?) be possible to get PHP builds running – just haven't had any time to look into getting a PHP bundle on Lambda.

Questions include whether we can try to get `phpenv` running, and what PHP binaries/scripts we install. `phpunit`, `Pyrus`, `pear`, `composer`?

**Comment by cweagans** [comment]
I'd say install composer by default. Most modern projects use Composer for dependency management, and they can pull in phpunit themselves. Pear is kinda meh. If you can include some prebuilt extensions that are off by default and have an easy way to turn them on, that would be pretty cool.

**Comment by Jonnx** [comment]
Composer installed by default will be really useful. Also support of both php7 and php5.6 will be extremely useful. There are many libraries and sdks form large software providers that do not support php7 (Salesforce, Quickbooks)

**Comment by cweagans** [comment]
<3

**Comment by mhart** [comment]
Ok, I've added support for PHP 7 and 5.6, with composer installed.

Picking an example PHP project, the Laravel framework builds and tests fine, you can see an example build here:

https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/140/3e9954f8a74dda5f4050b65bcf56cde8.html

In terms of config, it's pretty minimal – just the default `php-build` config options without CGI support (didn't really make sense to me to include this considering there's no apache, etc?). I think I'll need some more feedback on what a sane list of config options to include would be – without going over the top – but we can track that in other issues.

**Comment by Jonnx** [comment]
amazing. we use laravel so that is awesome! looking at using this for our build process now. already asked a few questions via issues. not sure if that the right way but super pumped about this.
