### ISSUE TITLE
Create stack fails with error "not authorized to perform: iam:PassRole on resource"

### ISSUE THREAD

**Issue by jakeg** [lambci/lambci#103]
Following the readme (and having successfully created a stack before in January), I get this error when trying to create the stack:

> Failed to create resource. User: arn:aws:sts::605034037838:assumed-role/lambci-LambdaExecution-1PR6HWHH4F78M/lambci-build is not authorized to perform: iam:PassRole on resource: arn:aws:iam::605034037838:role/lambci-SnsFailures-12A7PH6XYO1HO

This triggers a rollback, giving the stack the final status `ROLLBACK_COMPLETE`

**Comment by jakeg** [comment]
@Goblinlordx you seem to have had the [exact same problem](https://gitter.im/lambci/lambci?at=5afcdb09b84be71db912220d) a couple of weeks ago... did you have any luck in finding a solution?

**Comment by Goblinlordx** [comment]
I still have the same problem.  This being the case, I still haven't been able to use Lambci which I am actually quite sad about.  From what I looked into it, it looks like AWS might require PassRole when SNS uses some other service.  Honestly, I am nowhere near familiar enough with IAM to know what is going on though.  Also, seeing as others seem to have this up and running already, the whole thing is quite confusing.

Here is the reference I found concerning something possibly requiring PassRole:
https://docs.aws.amazon.com/systems-manager/latest/userguide/rc-sns-notifications.html#rc-send-notifications

The use case is definitely not the same though.  I really hope this can get worked out as I still would really like to try to use Lambci.

**Comment by jakeg** [comment]
@mhart I'm not sure where to start looking into this one as I haven't used AWS much before and the UX for setting up all the IAM stuff is just crazy - over 300 different roles. Any suggestions? My guess is this issue will affect any new installations of LambCI, so without a fix it's unusable for new projects :(

I thought this might have been something to do with AWS deprecating node v4.* (#76) but changing the version to v8.10 in the lambci template file does not fix this.

**Comment by mhart** [comment]
@jakeg @Goblinlordx I haven't actually tried to launch a stack in months – mine have just been humming along.

I'll try again now and see what the deal is.

**Comment by mhart** [comment]
Thanks guys – I guess AWS must have made something tighter on their end – this permission was never required before.

I've just pushed out a new version, 0.9.14 – please give that a shot and see if it works (I was able to replicate your problem and this fixed it for me)

I'm working on updating to Node.js 8.10 – the code itself won't need to change much (although I'd like to update everything to async/await at some point) – the larger issue is the change in system paths and libraries where I need to test that all of the native code: git, ruby, php, gcc, rust, etc still work

**Comment by jakeg** [comment]
Thanks @mhart - can confirm that I've now successfully deployed a new stack since your changes. Much appreciated :)
