### ISSUE TITLE
ProxyCommand setuid issue.

### ISSUE THREAD

**Issue by ispyinternet** [lambci/lambci#104]
Im using the git/ssh binary you have created and trying to connect via a jump server, but ProxyCommand is raising a setuid issue. Do you know if there is a workaround or fix available? 

````
OpenSSH_7.4p1, OpenSSL 1.0.1k-fips 8 Jan 2015
debug1: Reading configuration data /tmp/ssh_config
debug1: /tmp/ssh_config line 16: Applying options for bitbucker_server
debug1: Executing proxy command: exec /tmp/git/usr/bin/ssh -vvv -F /tmp/ssh_config inter -W bitbucket_server:7999
debug1: permanently_drop_suid: 482
setresuid 482: Operation not permitted
````

Thanks,

**Comment by mhart** [comment]
I'm not sure if there's a workaround or not – I haven't tried this.

Give https://github.com/lambci/git-lambda-layer a shot, and if it doesn't work, open an issue over there too.
