### ISSUE TITLE
TypeError: this is not a typed array. on first run

### ISSUE THREAD

**Issue by bhchance** [lambci/lambci#108]
I ran the setup procedures on the github page, including the .lambci.json for py27. I then try the clicking the "Test Service" button on github hook, and get an error:

```
$ rm -rf /tmp/lambci/build

/var/runtime/node_modules/aws-sdk/lib/request.js:31
throw err;
^

TypeError: this is not a typed array.
at Function.from (native)
at Object.exports.lineStream (/var/task/utils/index.js:114:25)
at runInBash (/var/task/actions/build.js:204:26)
at runCmd (/var/task/actions/build.js:166:29)
at /var/task/node_modules/async/internal/withoutIndex.js:9:16
at replenish (/var/task/node_modules/async/internal/eachOfLimit.js:66:17)
at /var/task/node_modules/async/internal/eachOfLimit.js:71:9
at eachLimit (/var/task/node_modules/async/eachLimit.js:43:36)
at Object.<anonymous> (/var/task/node_modules/async/internal/doLimit.js:9:16)
```

I wasn't sure if there was a better community to raise this issue in.

**Comment by mhart** [comment]
This is strange – it implies that AWS SDK is using `Buffer.from` – which was fixed way back in Dec 2016 (v2.7.24)

Can you tell me more about how you set this up – did you use the CloudFormation template? Did you check out from git and create it yourself, etc?

If you could give me the exact steps you used to launch your LambCI stack, that would help

**Comment by bhchance** [comment]
Yep, strange to me for the same reason. I checked the source and none of that code has been touched in years, which means it should be fairly stable, especially for straight OOB scenarios.

I used the "spin up a CloudFormation stack" link in the Installation section. I added my GitHub Token and repo, no slack. That was all I set. Then I changed `.lambci.json` to:
```
{
  "cmd": "pip install --user tox && tox"
}
```
And that's it, lambci-wise. Other than that I just worked to get tox setup.

**Comment by mhart** [comment]
Hmmm – ok, there might have been an issue with some node_modules erroneously being packaged in the zip file.

I've rebuilt it and uploaded to S3 again. So try deploying the CloudFormation stack again and let me know if that fixes the problem.

**Comment by bhchance** [comment]
I'm getting failures on installing pip dependencies now, so it looks like the original issue is fixed and it's all on my end now.

Thanks!

**Comment by mhart** [comment]
Great, thanks for reporting!
