### ISSUE TITLE
Add Ruby support

### ISSUE THREAD

**Issue by mhart** [lambci/lambci#11]
Haven't looked at this at all, but similar to other langs, it should be totally possible.

Just a question of whether we try to support `rvm` (probably) or `rbenv`, etc.

**Comment by rickhull** [comment]
I'd suggest starting with `rbenv` or `chruby` for their smaller footprint and complexity relative to `rvm`

**Comment by mhart** [comment]
@rickhull nice – I actually went with `nave` over `nvm` for the same reason. I just saw that Travis uses rvm so thought that might be a better choice (I also saw that they have prebuilt binaries which I thought might be easier on Lambda) – but yeah, will hopefully get a chance to look at this in the next couple of days

**Comment by fernandes** [comment]
@mhart I've been creating pre-built ruby packages (based on rbenv) to make installations faster, if I can help with something, just tell me

**Comment by mhart** [comment]
@fernandes interesting – what have you been doing for dependencies like libyaml, etc? Do you include them in the pre-built packages, or do you assume the system already has them?

**Comment by fernandes** [comment]
@mhart in our case, I put libraries as dependencies for rbenv package, and everything is ok

but, ruby can be compiled with static linkage, then there's no need for additional deps (but bigger binary)

makes sense?

**Comment by mhart** [comment]
Ok, so I've made some progress. Here's what works so far:

```bash
# Install rbenv
git clone --depth 1 https://github.com/rbenv/rbenv.git ~/.rbenv

# Add this plugin to download prebuilt binaries
git clone --depth 1 https://github.com/garnieretienne/rvm-download.git ~/.rbenv/plugins/rvm-download

# Set paths and env correctly for rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Download compatible binaries – centos 6 is compatible with amazon linux:
# So all versions at https://rvm.io/binaries/centos/6/x86_64/ should work
SYSTEM_NAME=centos SYSTEM_VERSION=6 rbenv download 2.2.1

rbenv local 2.2.1
gem install bundler
bundle --version
```

Here's the problem: this list of prebuilt binaries is pretty small, and not up to date – the latest is ruby 2.2.1 and a number of gems aren't compatible with a version that old (I get errors building projects like: `Gem::InstallError: rack requires Ruby version >= 2.2.2`)

So does anyone have a source of more up-to-date ruby binaries that will work with Amazon Linux (or CentOS or possibly even Fedora)?

**Comment by fernandes** [comment]
I don't know, I created my own debian repo :~

for ubuntu (I don't know if it's easier to change the distro or build the package, anyway...) you can get from: http://rubies.travis-ci.org/

**Comment by mhart** [comment]
Alright, I have Ruby working!

I've compiled the following versions which can be installed with `rbenv`:

* 2.3.1
* 2.2.5
* 2.1.9
* 2.0.0-p648

There's documentation here: https://github.com/lambci/lambci#ruby

[Here's a log](https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/75/bc1fd046c67d06bcbe2daa32b08970c1.html) of a build of the [chunky_png](https://github.com/wvanbergen/chunky_png) project.

So all up the bootstrap time is around 15 secs. A large part of that is bundler installing I think – the rbenv and ruby downloads are quite quick.

I'll look at including `rbenv` in LambCI itself so it doesn't need to be bootstrapped – but I don't think there's any way we'll include all (or any) of the Ruby binaries, so I think they'll always need to be bootstrapped – we might just look at making it a little cleaner if we ever develop language-specific support.

Closing this for now, but we can open more issues to refine the way we support Ruby

**Comment by ksaynice** [comment]
@mhart do you have any idea why I am getting 'Permission denied' issue? 
```
 $ ./build-ruby.sh
/bin/bash: ./build-ruby.sh: Permission denied
Command "./build-ruby.sh" failed with code 126
```

**Comment by ksaynice** [comment]
@mhart do you have any idea what is the best way to setup ci with private repo since I am getting this now
```
$ ./build-ruby.sh
+ rm -rf /tmp/maisi_website
+ git clone --depth 1 https://github.com/ksaynice/maisi_website.git /tmp/maisi_website
Cloning into '/tmp/maisi_website'...
fatal: could not read Username for 'https://github.com': No such file or directory
Command "./build-ruby.sh" failed with code 128
```

**Comment by mhart** [comment]
@ksaynice you shouldn't be cloning the repo explicitly – as the comment in that file says, I'm only cloning that repo as an example. If you set your repo up with LambCI, then you'll already be in the repo directory when the build starts.

**Comment by ksaynice** [comment]
@mhart gotcha, and thanks for the fast respond

**Comment by ksaynice** [comment]
now I am having trouble while bundle trying install gems from github repo, I guess it through SSH instead of https, so I wondering if the github token I have been setup before would work with it even I set access public repo permission for it.
see backtrace here:
```
Build #6 started...

Branch log: https://lambci-buildresults-70839mch26l.s3.amazonaws.com/gh/ksaynice/maisi_website/branches/master/1cb69a11ac6acffd237a5a74d153de23.html
Branch status img: https://lambci-buildresults-70839mch26l.s3.amazonaws.com/gh/ksaynice/maisi_website/branches/master/0a44b0faf883cdcc998c36149e757e99.svg
Build log: https://lambci-buildresults-70839mch26l.s3.amazonaws.com/gh/ksaynice/maisi_website/builds/6/f9dd200a3eea2b4f6a94d795d80dfbc6.html

$ ./build-ruby.sh
+ VERSION=2.3.1
+ tar -C /tmp/lambci/home -xz
+ curl -sSL https://lambci.s3.amazonaws.com/binaries/libyaml-2.0.4.tgz
+ '[' -d /tmp/lambci/home/.rbenv ']'
+ git clone --depth 1 https://github.com/rbenv/rbenv.git /tmp/lambci/home/.rbenv
Cloning into '/tmp/lambci/home/.rbenv'...
+ export PATH=/tmp/lambci/home/.rbenv/bin:/tmp/lambci/home/.local/bin:/tmp/lambci/home/usr/bin:/var/task/vendor/python/bin:/var/task/node_modules/.bin:/usr/local/lib64/node-v4.3.x/bin:/usr/local/bin:/usr/bin/:/bin
+ PATH=/tmp/lambci/home/.rbenv/bin:/tmp/lambci/home/.local/bin:/tmp/lambci/home/usr/bin:/var/task/vendor/python/bin:/var/task/node_modules/.bin:/usr/local/lib64/node-v4.3.x/bin:/usr/local/bin:/usr/bin/:/bin
++ rbenv init -
+ eval 'export PATH="/tmp/lambci/home/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '\''/tmp/lambci/home/.rbenv/libexec/../completions/rbenv.bash'\''
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}'
++ export PATH=/tmp/lambci/home/.rbenv/shims:/tmp/lambci/home/.rbenv/bin:/tmp/lambci/home/.local/bin:/tmp/lambci/home/usr/bin:/var/task/vendor/python/bin:/var/task/node_modules/.bin:/usr/local/lib64/node-v4.3.x/bin:/usr/local/bin:/usr/bin/:/bin
++ PATH=/tmp/lambci/home/.rbenv/shims:/tmp/lambci/home/.rbenv/bin:/tmp/lambci/home/.local/bin:/tmp/lambci/home/usr/bin:/var/task/vendor/python/bin:/var/task/node_modules/.bin:/usr/local/lib64/node-v4.3.x/bin:/usr/local/bin:/usr/bin/:/bin
++ export RBENV_SHELL=bash
++ RBENV_SHELL=bash
++ source /tmp/lambci/home/.rbenv/libexec/../completions/rbenv.bash
+++ complete -F _rbenv rbenv
++ command rbenv rehash
+ echo 'gem: --no-document'
+ echo '--color --tty'
+ '[' -d /tmp/lambci/home/.rbenv/versions/2.3.1 ']'
+ tar -C /tmp/lambci/home/.rbenv/versions -xz
+ curl -sSL https://lambci.s3.amazonaws.com/binaries/ruby-2.3.1.tgz
+ rbenv rehash
+ local command
+ command=rehash
+ '[' 1 -gt 0 ']'
+ shift
+ case "$command" in
++ rbenv sh-rehash
++ local command
++ command=sh-rehash
++ '[' 1 -gt 0 ']'
++ shift
++ case "$command" in
++ command rbenv sh-rehash
++ rbenv sh-rehash
+ eval 'hash -r 2>/dev/null || true'
++ hash -r
+ rbenv local 2.3.1
+ local command
+ command=local
+ '[' 2 -gt 0 ']'
+ shift
+ case "$command" in
+ command rbenv local 2.3.1
+ rbenv local 2.3.1
+ gem install bundler
Successfully installed bundler-1.12.5
1 gem installed
+ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Fetching git@github.com:ActsAsParanoid/acts_as_paranoid.git
PRIV_END: seteuid: Operation not permitted
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone 'git@github.com:ActsAsParanoid/acts_as_paranoid.git' "/tmp/lambci/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/cache/bundler/git/acts_as_paranoid-9f5cd34ede152d37968c179cab0abea94c646db4" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:ActsAsParanoid/acts_as_paranoid.git' "/tmp/lambci/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/cache/bundler/git/acts_as_paranoid-9f5cd34ede152d37968c179cab0abea94c646db4" --bare --no-hardlinks --quiet` in directory /tmp/lambci/build/ksaynice/maisi_website has failed.
PRIV_END: seteuid: Operation not permitted
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone 'git@github.com:ActsAsParanoid/acts_as_paranoid.git' "/tmp/lambci/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/cache/bundler/git/acts_as_paranoid-9f5cd34ede152d37968c179cab0abea94c646db4" --bare --no-hardlinks --quiet due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:ActsAsParanoid/acts_as_paranoid.git' "/tmp/lambci/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/cache/bundler/git/acts_as_paranoid-9f5cd34ede152d37968c179cab0abea94c646db4" --bare --no-hardlinks --quiet` in directory /tmp/lambci/build/ksaynice/maisi_website has failed.
PRIV_END: seteuid: Operation not permitted
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone 'git@github.com:ActsAsParanoid/acts_as_paranoid.git' "/tmp/lambci/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/cache/bundler/git/acts_as_paranoid-9f5cd34ede152d37968c179cab0abea94c646db4" --bare --no-hardlinks --quiet due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:ActsAsParanoid/acts_as_paranoid.git' "/tmp/lambci/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/cache/bundler/git/acts_as_paranoid-9f5cd34ede152d37968c179cab0abea94c646db4" --bare --no-hardlinks --quiet` in directory /tmp/lambci/build/ksaynice/maisi_website has failed.
PRIV_END: seteuid: Operation not permitted
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Git error: command `git clone
'git@github.com:ActsAsParanoid/acts_as_paranoid.git'
"/tmp/lambci/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/cache/bundler/git/acts_as_paranoid-9f5cd34ede152d37968c179cab0abea94c646db4"
--bare --no-hardlinks --quiet` in directory
/tmp/lambci/build/ksaynice/maisi_website has failed.
Build #6 failed: Command "./build-ruby.sh" failed with code 11
```

**Comment by mhart** [comment]
Hmmm, interesting – I'm not exactly sure what that "PRIV_END: seteuid: Operation not permitted" error is – it's possible that git is trying to write a file somewhere that it doesn't have access to...? I'll look into this!

**Comment by mhart** [comment]
@ksaynice ugh, ok, this is looking not so good – so with a `git@github.com` address, `git` will use `ssh` to clone the directory.

The problem is, `ssh` is trying to create a `.ssh` directory in `/home/sbx_user1051/` instead of respecting the `HOME` env variable (which should be `/tmp/lambci/home`) – but it doesn't have access to  `/home/sbx_user1051/` – so it fails with a permission error.

I'm looking to see if there's *any* way we can get ssh to respect the HOME variable, but if not, then it might not be possible to clone repositories using `git@github.com` addresses – you might need to stick to `https://github.com` addresses 😕

**Comment by mhart** [comment]
@ksaynice ok, I've figured out a way to get ssh working with github on Lambda.

Basically, you can export a `GIT_SSH_COMMAND` which `git` will use whenever it wants to talk ssh. This means that you can provide your own path to a key, known_hosts, etc.

I'm looking into generating an ssh key that all LambCI users can use. But until then you could provide your own key (create a throwaway GitHub user for this – don't use your own personal key unless you know what you're doing!), for example:

```bash
export GIT_SSH_COMMAND="ssh -i $PWD/path/to/private/id_rsa -o UserKnownHostsFile=$PWD/path/to/known_hosts"
```

Or to turn off host checking:

```bash
export GIT_SSH_COMMAND="ssh -i $PWD/path/to/private/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
```

Then you should be able to clone GitHub repos using the `git@github.com:user/repo.git` notation.

Again, I'll make this easier and add some documentation about it.

**Comment by mhart** [comment]
@ksaynice opened an issue at #26 to track this – let's move any conversation about ssh stuff over there

**Comment by ksaynice** [comment]
@mhart sounds good, thanks for the help, and I really like the idea that you will create a user and have a SSH for it that all LambCi user can use :)
