### ISSUE TITLE
How to build a more up to date git?

### ISSUE THREAD

**Issue by mnapoli** [lambci/lambci#110]
I would like to use git 2.5 to be able to do shallow clones for specific commits (see https://stackoverflow.com/a/43136160/245552).

I couldn't find any Dockerfile or build file to compile git. Do you remember how you did it? I am trying to compile myself but no luck yet (git compiles OK but I'm a bit lost at which files I should get from my container, I'm pretty sure just copying the `git` binary is not enough).

**Comment by mhart** [comment]
https://github.com/lambci/git-lambda-layer should have everything you need

**Comment by mnapoli** [comment]
@mhart this is awesome, thank you!
