### ISSUE TITLE
"php: error while loading shared libraries: libtidy-0.99.so.0"

### ISSUE THREAD

**Issue by Narno** [lambci/lambci#116]
Hello here!

I'm using lambci for many months with my static site generator and it's very effective: I love it! :-)
(ref: https://github.com/Narno/narno.com/blob/master/.lambci.json)

But since a few weeks, PHP doesn't works anymore cause of:
> php: error while loading shared libraries: libtidy-0.99.so.0: cannot open shared object file: No such file or directory

<details><summary>Click to see full build log</summary>
<p>

```bash
LambCI v0.9.14 triggered on stack "lambci"

Looking up keys in lambci-config: global, gh/Narno/narno.com

$ rm -rf /tmp/lambci/build
$ git clone --depth 5 https://github.com/Narno/narno.com.git -b master /tmp/lambci/build/Narno/narno.com
Cloning into '/tmp/lambci/build/Narno/narno.com'...
$ cd /tmp/lambci/build/Narno/narno.com && git checkout -qf e082386be84c65b5cefb47369726d2bd3c4c570e

Build #98 started...

Branch log: https://lambci-buildresults-1w0y4nab0105t.s3.amazonaws.com/gh/Narno/narno.com/branches/master/21a79e65d8719f0e3e4f032a47a8c26a.html
Branch status img: https://lambci-buildresults-1w0y4nab0105t.s3.amazonaws.com/gh/Narno/narno.com/branches/master/d968dc9e875fbd4e53e47bde3ace533b.svg
Build log: https://lambci-buildresults-1w0y4nab0105t.s3.amazonaws.com/gh/Narno/narno.com/builds/98/7e2a3f5f325d7b90e8463e9df671ff24.html

$ chmod +x ./scripts/lambci.sh && ./scripts/lambci.sh
Installing PHP 7.1.2...
++ mkdir -p /tmp/lambci/home/.phpenv/versions
++ tar -xz -C /tmp/lambci/home/.phpenv/versions
++ curl -sSL https://lambci.s3.amazonaws.com/binaries/php-7.1.2.tgz
++ set +x
php: error while loading shared libraries: libtidy-0.99.so.0: cannot open shared object file: No such file or directory
Build #98 failed: Command "chmod +x ./scripts/lambci.sh && ./scripts/lambci.sh" failed with code 127
```

</p>
</details>

(ref: [direct link](https://lambci-buildresults-1w0y4nab0105t.s3.amazonaws.com/gh/Narno/narno.com/builds/98/7e2a3f5f325d7b90e8463e9df671ff24.html))

Is any body has an idea to fix that? Thanks a lot.

**Comment by mhart** [comment]
@Narno can you try building again? I think the latest libtidy tarfile on s3 had the wrong filesystem layout

**Comment by Narno** [comment]
Yeah, it work fine:
```bash
PHP 7.1.2 (cli) (built: Apr 13 2017 16:22:22) ( NTS )
[...]
PHP setup complete
```
(build log: https://s3.amazonaws.com/lambci-buildresults-1w0y4nab0105t/gh/Narno/narno.com/branches/master/21a79e65d8719f0e3e4f032a47a8c26a.html)

Thanks a lot @mhart! :kissing_heart:
