### ISSUE TITLE
README section on large pushes not triggering is now redundant

### ISSUE THREAD

**Issue by chuckoy** [lambci/lambci#119]
The section on [builds not triggering on large pushes](https://github.com/lambci/lambci#why-isnt-my-build-triggering-on-large-pushes) is I believe redundant as AWS now supports [256KB asynchronous invocation payloads](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-doubles-payload-size-for-asynchronous-invocations/). With this, SNS and Lambda payload size limits should now be in line and the error will no longer occur.

**Comment by mhart** [comment]
Was removed a while ago in the 0.10.0 branch – just haven't had time to merge yet. https://github.com/lambci/lambci/commit/427ead03e64068a07dfa7a6a961443c7a49f0083#diff-04c6e90faac2675aa89e2176d2eec7d8
