### ISSUE TITLE
Add support for multiple Python versions

### ISSUE THREAD

**Issue by mhart** [lambci/lambci#12]
Python 2.7 is already installed on Lambda, but it would be good to explore support for Python 3 – possibly through `pyenv`

**Comment by ngfgrant** [comment]
Hi @mhart 👋 

Is this issue still relevant given Lambda now fully supports Python 3? If not then let me know what I can do to help move this issue forward! If Python 3 is now supported then the readme could be updated under "Supported Languages"?

Cheers,
Niall

**Comment by agmnjdby** [comment]
Hi @mhart,

Could you please suggest best way change configuration for default build to support Python 3.6.1 builds as right now we did try configurationn changes but no success.

Did lambci support python 3.6.1 builds?

Let me know of your input. Many thanks.

Regards,
Manuj

**Comment by mhart** [comment]
Done as of 0.10.0
