### ISSUE TITLE
Different build commands for push vs release?

### ISSUE THREAD

**Issue by cjmaria** [lambci/lambci#122]
Is there a way to issue different build steps for a git push versus a release?
Ex: When there is a push, I want to build with `. ~/init/python 3.7.2 && pip install --user tox && tox`, but when there is a release, I would like to build with `. ~/init/python 3.7.2 && pip install --user tox && tox && python deploy.py`

**Comment by mhart** [comment]
Not out of the box, no – you'd need to modify LambCI to be able to respond to Release events: https://developer.github.com/v3/activity/events/types/#releaseevent – at the moment it only responds to push or pull-request events.
