### ISSUE TITLE
The use cases of Lambda CI? 

### ISSUE THREAD

**Issue by x1angli** [lambci/lambci#124]
(Warning: rant and rave ahead.... )

I found this repo weeks ago where I was struggling building a CI-like project with Amazon Lambda. This repo is great, definitely. Your wonderful lambci saved me 100 hours by providing helpful tips and examples (especially the LambdaCI layer). Thank you! 

However, it downed upon me that it might be better to switch to Amazon ECS or other docker-based systems. It's also worthwhile to try CircleCI / TravisCI. The reason behind this: AWS lambda is designed for stateless, lightweight tasks, while CI is stateful and usually IO-heavy. Even with the lambci project, devops still have to spend lots of time on overcoming the limitations imposed by AWS lambda, such as:  read-only file system, very counter-intuitive requirements of placing python modules inside the deployment package, etc.... Time is costly. I would rather pay for ECS or subscribe to a CircleCI plan than spending time on Lambda walkarounds.

I believe you guys must have very good reasons to stick to Lambda for CI. Demonstration of lambci's use cases would be highly appreciated.

**Comment by mhart** [comment]
Sounds like AWS CodeBuild does exactly what you want: https://aws.amazon.com/codebuild/

LambCI is useful for any domain in which you're not limited in the ways you list (although I'm confused about your "placing the python modules inside deployment package" statement – you can just install them with `pip` in your LambCI build).

I disagree with some of your other statements: Besides caching (which you can do on S3), your CI should *not* be stateful. Statefulness introduces reproducibility issues into your build process. Also, Lambda excels at I/O – speeds are *very* fast from S3 for example – so I'm not sure what you're referring to there.

The one big difference between LambCI and other CI offerings is performance – especially with parallel processes. You can split your build into 1000 different steps and run them all in parallel and have it finish in seconds. You can't do that with any other CI system that I'm aware of (unless you build your own cluster)

However, I'm certainly not advocating that you use LambCI if it's not right for your project – and that goes for any system you want to run on Lambda too.

**Comment by x1angli** [comment]
Thanks a lot

I am particularly intrigued by the S3 part. I am curious about how S3 plays a role in LambCI (or any CI system that is based on Lambda)

Could you please elaborate how we can do caching on S3? 
What is cached here? (the HEAD commit, a git branch, or the build artifacts) ? 

The reason for asking this dumb question is, as far as I know, Lambda does not allow mounting S3 as part of Linux file system, so we cannot manipulating S3 in the same way as a local file. Such design makes S3-based file I/O very inconvenient.... 

> Besides caching (which you can do on S3)
> Lambda excels at I/O – speeds are very fast from S3 for example

**Comment by x1angli** [comment]
sorry for the confusion made by me in the original post

by mentioning 

> very counter-intuitive requirements of placing python modules inside the deployment package

I was referring to the fact that, after installing python modules with `pip` , those python packages are located under `./venv/site-packages` folder of the deployment package , but AWS' deployment package spec requires those packages located under the root folder of the deployment package, so that whenever making a build, I have to move the folders of those python packages.

Of course, this is just a single line  of `mv` command in my CI script of making a new AWS Lambda deployment package
