### ISSUE TITLE
Unable to use nave to change the current node.js version

### ISSUE THREAD

**Issue by raman-trantor** [lambci/lambci#127]
I am trying to change the node version being used by using 'nave use 10' in `cmd` parameter but it's always throwing the following exception:

```
#############################                                             41.6%
######################################################################## 100.0%
/var/task/node_modules/.bin/nave: line 246: shasum: command not found
shasum mismatch, expect 6c35b85a7cd4188ab7578354277b2b2ca43eacc864a2a16b3669753ec2369d52, got 6c35b85a7cd4188ab7578354277b2b2ca43eacc864a2a16b3669753ec2369d52

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Binary install failed, trying source.
```
Please let me know if I am doing something wrong or somethings have changed on the lambda end due to which the issue is occurring.

**Comment by mhart** [comment]
Ugh, yeah I just noticed `nave` added that `shasum` check to one of it's recent versions. Have updated LambCI to v0.10.1 to fix it. Sorry for the hassle!

**Comment by raman-trantor** [comment]
Thanks, @mhart. I suppose I'll need to follow the update process mentioned in README to fix this for an already running LambCI instance. Please correct me if I am wrong.

**Comment by mhart** [comment]
Yeah that's right – assuming you launched your stack using the template hosted on LambCI's S3 bucket – that template has been updated so you should just be able to use that again and everything Should Work™
