### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by GordonSo** [lambci/lambci#138]
Sorry in advance, as I noticed the mention of repo in maintenance mode, but I'm not seeing further updates [here](https://github.com/lambci/lambci#language-recipes) so please let me know if I can contribute in other places. 

AWS now [support](https://aws.amazon.com/tw/about-aws/whats-new/2021/08/aws-lambda-adds-support-python-3-9/) Python 3.9

But upon using "serverless deploy" on a pipenv/ serverless package with Python3.9, I got to this error:
```
Unable to find image 'lambci/lambda:build-python3.9'
```

And I gather it is something with [lambdci/docker-lambda](https://github.com/lambci/docker-lambda), and mimick the Python 3.8 PR for 3.9, see: https://github.com/lambci/docker-lambda/pull/348

However, an image needs to be pushed through to lambci.s3.mazon.com first, 
```
docker.io/lambci/lambda:python3.9: not found
```

An attempted PR is added ([see](https://github.com/lambci/lambci/pull/139)), but I am guessing it needs to be executed by somebody with access to that AWS account with that lambci s3 bucket?

Appreciate your great work and your attention!

**Comment by migurski** [comment]
I’m also very interested to see a Python 3.9 lambda image. I use these to compile executable packages for use on Lambda.

**Comment by tb102122** [comment]
the PR https://github.com/lambci/lambci/pull/139 is already existing but nobody is approving it.

**Comment by mrubelmann** [comment]
Hmm...  #139 has been approved, but not merged.  @mhart, have you considered merging it?  It would be a great help if you could!

**Comment by mrubelmann** [comment]
For anyone else who landed here looking for Python 3.9 support, I want to point out that I had success with mLupine's fork of lambci/docker-lambda.  Hopefully #139 will get merged, but if not, this container works like a charm:

https://hub.docker.com/r/mlupin/docker-lambda

**Comment by ykravch** [comment]
Hello. Do you have any updates on this?

**Comment by tb102122** [comment]
@ykravch start using https://hub.docker.com/r/mlupin/docker-lambda

**Comment by atjshop** [comment]
I had same issue, here is what in the yaml file:

provider:
    name: aws
    runtime: python3.9

And below is the error I got when deploy:
Serverless: Stderr: Unable to find image 'lambci/lambda:build-python3.9' locally

how can I config to use image here https://hub.docker.com/r/mlupin/docker-lambda?

thanks.

**Comment by tb102122** [comment]
@atjshop mlupin/docker-lambda:python3.9-build

**Comment by steveinatorx** [comment]
for newbs confused by @tb102122's comment - you can use a custom docker image like this in serverless.yml:

`custom:
  pythonRequirements:
    dockerImage: mlupin/docker-lambda:python3.9-build
    slim: true
    layer: true
`
i was able to get python 3.9 to properly run in serverless lambda using this

**Comment by psaks** [comment]
Or use the official image from AWS ...

https://gallery.ecr.aws/sam/build-python3.9

`public.ecr.aws/sam/build-python3.9:latest`

**Comment by mhart** [comment]
I think you might all be confusing this project (which is a CI project built on Lambda) with https://github.com/lambci/docker-lambda

**Comment by rnag** [comment]
Just a note, for those using CDK. I use this snippet a lot in my projects, and just now adapted it to use the official AWS images for `pip install`s, as outlined above. Feel free to check it out, and leave a star or add comments if anyone find it useful.

https://gist.github.com/rnag/a82a4892e670182ca9c68ab624ce4756
