### ISSUE TITLE
Add Java 1.7 support

### ISSUE THREAD

**Issue by mhart** [lambci/lambci#14]
Lambda comes with Java 7 and 8 JREs but no SDKs (ie, no `javac`)

Will need to research to see how doable this is – if there's even enough disk space to get everything on there...?

EDIT: Have gotten Java 1.8 building, just need to create a package for 1.7

**Comment by digitalsanctum** [comment]
Hi, I'm willing to help with this issue. Do you have an idea of how you'd like to proceed?

My first thought is to provide pared down the OpenJDK binaries which could be stored in S3. Provide a bootstrap class with configuration to point to S3 bucket and pull them in and add symlinks.

Agreed that even pared down binaries along with optional maven, gradle, etc. will take up a fair bit of the available 500MB of disk space. That being said I think this can be addressed by having good documentation around the limits.

**Comment by mhart** [comment]
Yep, that's pretty much along the lines I was thinking

I've been testing something like that, and then trying to use `RxJava` as an example – which uses `gradle` – but I keep running into a problem where gradle is searching in the `jre` directory for `tools.jar` instead of respecting my `JAVA_HOME` (which has a `lib/tools.jar`)

So, I have `JAVA_HOME` set to `/tmp/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.77-0.b03.9.amzn1.x86_64` – which has a valid SDK installation, aside from `/tmp/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.77-0.b03.9.amzn1.x86_64/jre` being a symlink to `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.77-0.b03.9.amzn1.x86_64/jre`


```
java.lang.IllegalStateException: Could not find tools.jar. Please check that /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.77-0.b03.9.amzn1.x86_64/jre contains a valid JDK installation.
        at org.gradle.internal.jvm.JdkTools.<init>(JdkTools.java:57)
        at org.gradle.internal.jvm.JdkTools.current(JdkTools.java:44)
...
```

I mean, aside from that most of what I've tried works – `java` and `javac` seem to execute fine – perhaps it's a matter of finding the right env variables to set – or it could even be a bug with `gradle`

**Comment by digitalsanctum** [comment]
Can we rely on environment variables being respected or hanging around between invocations? Might be better to precede calls to gradle with JAVA_HOME=/path/to/jdk or using some other means to let gradle know which JDK to use.

**Comment by mhart** [comment]
I'm doing all this in a bash script – so it's setting it just before it invokes gradle.

It's got to be something to do with the fact that I'm symlinking the `jre` in – copying it over seems to work a lot better.

Perhaps I can reconstruct the entire jre directory just as symlinks!

**Comment by mhart** [comment]
You can see an example of it working here (with https://github.com/jhalterman/failsafe which uses Maven):

https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/88/90de8b960067fbf36ad2f4bd49080c77.html

Still not 100% happy with the fact that I'm copying the entire `jre` directory that already exists – will work on that.

Still, it builds! Twice as fast as Travis too 😉  – https://travis-ci.org/jhalterman/failsafe

**Comment by mhart** [comment]
Ok, so from trial and error it seems that the one file that has to be physically present (can't be symlinked) is `$JAVA_HOME/jre/lib/amd64/server/libjvm.so` – but everything else can be symlinked to save space.

See example here: https://github.com/mhart/test-ci-project/commit/a5dbc8078d191d4155af81da0d6aa7dd56ade840

Next step, Java 1.7!

**Comment by digitalsanctum** [comment]
I'm actively working on getting 1.7 working. Couple questions:

1. I'm having an issue with is finding an official version of the OpenJDK 1.7 binaries. Any suggestions on where to source these?
2. Should we remove the JRE directory from the binary since we're symlinking anyway?

**Comment by mhart** [comment]
@digitalsanctum sorry for the delay, just had to push up the tarball. Have gotten this working and reworked the bash script ever so slightly to make it easier to swap versions:

https://github.com/mhart/test-ci-project/blob/799019304f69c6b0392b8bb7b52750a7e089e7b2/build-java-1.7.sh

Example build is here:

https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/116/3268a50e1a26198fcfa8b07ab05606ee.html

I'll update the README and then close this out 👍
