### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by thanakijwanavit** [lambci/lambci#140]
Hi as you may know, aws has released support for [lambda on arm64](https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/) which is quite a big deal because the running cost is a lot lower. Would you be interested in supporting it? I for one would really appreciate the support.

I may not have the expertise to make the pr myself but I would be happy to attempt one. Just wondering if anyone is already working on it or would be interested to.

**Comment by mhart** [comment]
I think you might be confusing this project (which is a CI project built on Lambda) with https://github.com/lambci/docker-lambda
