### ISSUE TITLE
Still no python 3.9 yet Python 3.11 just released with huge speed improvements

### ISSUE THREAD

**Issue by Paul-J-Barrett** [lambci/lambci#143]
Running into issues finding appropriate node:18-alpine that will work with serverless and python3.8.
Started down  the road of changing things over to 3.9 and realized that I had seen tickets for 3.9 not being supported yet.

Going with node:18-bullseye which has 3.9 built in to build the serverless deployment and create the lambda layers which serverless does. Hope it all works.

**Comment by mhart** [comment]
I think you might be confusing this project (which is a CI project built on Lambda) with https://github.com/lambci/docker-lambda
