### ISSUE TITLE
Package dependency issue

### ISSUE THREAD

**Issue by pawanreddy1708** [lambci/lambci#144]
Hi Team,

After deploying the code with serverless and lambci, I am facing package dependency issue as mentioned below:

Something went wrong in group actions with: Cannot load native module 'Crypto.Hash._MD5': Not found '_MD5.cpython-39-x86_64-linux-gnu.so', Cannot load '_MD5.abi3.so': /var/task/Crypto/Util/../Hash/_MD5.abi3.so: invalid ELF header, Not found '_MD5.so' | [ERROR] 2023-03-13T10:09:50.383Z f9581912-79fd-42a4-a00b-0745d599588a Something went wrong in group actions with: Cannot load native module 'Crypto.Hash._MD5': Not found '_MD5.cpython-39-x86_64-linux-gnu.so', Cannot load '_MD5.abi3.so': /var/task/Crypto/Util/../Hash/_MD5.abi3.so: invalid ELF header, Not found '_MD5.so'
-- | --

**Comment by mhart** [comment]
LambCI is a serverless CI tool, written in JavaScript. You might be referring to https://github.com/lambci/docker-lambda which has been deprecated in favor of AWS' official images at https://github.com/aws/aws-lambda-base-images
