### ISSUE TITLE
gitlab support

### ISSUE THREAD

**Issue by posix4e** [lambci/lambci#15]
I feel the winds of gitlab coming, We are trying it where I work.

**Comment by mrjk05** [comment]
Any support for Gitlab yet?

**Comment by kadima1** [comment]
# **GITLAB**

**Comment by hery84** [comment]
GitLab++

**Comment by mozinrat** [comment]
Still awaiting support for gitlab 👍

**Comment by THPubs** [comment]
Would be great if we can have this feature!

**Comment by BordelD** [comment]
Add support for gitlab, please!

**Comment by dazza-codes** [comment]
This issue needs to be linked to a related issue on gitlab - the gitlab team need an issue for visibility and management of the workflow to get it done - they would have to provide/modify their runner to work with AWS Lambda, if they haven't already.  A quick search finds something related in https://gitlab.com/msvechla/gitlab-lambda-runner
