### ISSUE TITLE
I can haz readme shields?

### ISSUE THREAD

**Issue by dawsonbotsford** [lambci/lambci#22]
`build passing` in green
`build failling` in red

**Comment by mhart** [comment]
@dawsonbotsford Yep, these exist – you can see that LambCI has one on the README for itself – they're just not documented very well.

You can see the URL for a particular branch's status shield in the build log – that URL won't change for that particular branch.

I'll keep this open until I document it better

**Comment by mhart** [comment]
Thanks for reporting @dawsonbotsford – finally got around to documenting this: https://github.com/lambci/lambci#build-status-badges
