### ISSUE TITLE
Rust install is too large – find minimal Rust installation?

### ISSUE THREAD

**Issue by mhart** [lambci/lambci#24]
Unfortunately, the size of Rust is too typically large to unpack into Lambda, along with gcc and cargo and cargo dependencies.

Lambda currently only has 500MB scratch space in `/tmp`, and Rust is around 300MB

If we could find a Rust installation that's a third of the size, we'd have more room to play with

**Comment by chris-morgan** [comment]
You’ll note that for each file in `lib/lib*.so` there is an equivalently-named file in `lib/rustlib/x86_64-unknown-linux-gnu/lib/` (for whatever host toolchain you have). They aren’t identical, but as I recall it it’s only in the metadata that they differ (rustc doesn’t yet produce bit-level reproducible builds), so you can just ditch all the `lib/lib*.so` ones and make them symlinks of the others. This saves ~110MB.

I’m presuming you’ve already ditched the /etc and /share parts of the distribution, given the 300MB figure you cite.

I think that’ll be it for the *easy* wins. Not sure if rustc can be conveniently dynamically linked, and if so whether it gets you much space saving. I’ll point some others who may know in this direction.

Feel free to summon me if you have any more Rust questions at any point. I can help point you in the right direction, if nothing else. Come to #rust on Mozilla IRC, too—we’re a friendly bunch there!

**Comment by mhart** [comment]
Oooh, nice tip – I'll definitely check that out! Yeah, have ditched everything else pretty much – from memory it was mostly `.so` files taking up the bulk of the remaining space.

**Comment by chris-morgan** [comment]
That seems to be all the low-hanging fruit. In https://www.reddit.com/r/rust/comments/4s97yh/challenge_produce_the_smallest_possible_rustc/ we came up with a couple of suggestions for optimising space used in crate dependencies, but nothing especially easy to implement or particularly likely to save a great deal of space. Compiled artefacts are far and away the largest part of any such thing.

**Comment by chris-morgan** [comment]
Just to clarify things on the lib files: lib/lib*.so is host architecture, used by rustc (which is dynamically linked by default). lib/rustlib/TARGET is target architecture files; in it, the .rlib files are necessary, the .so files are only necessary for dynamic linking (static linking is the default). You can actually ditch the .so files altogether if you only support static linking, but that is functionally limiting and so off the table. It’s possible to have multiple targets (rustc has great cross-compilation support), and it’s *possible* to not have a target toolchain matching the host system (such a configuration would only support cross-compilation, not compilation for the host architecture), though in practice I doubt anyone has a cross-compilation-only setup.

**Comment by mhart** [comment]
Nice, all great suggestions – I managed to get it down to around 140MB after doing the symlinking, which is not too bad, probably good enough to close this.

Have added some documentation on how to build here: https://github.com/lambci/lambci#rust

Here's an example build of `mio`:

https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/120/9b033a751bbd9543ddae89122993bc6c.html

**Comment by rubo77** [comment]
Would this work on Unbuntu too?

Can you provide a bash script that minimizes the rust-installation install on my system?
