### ISSUE TITLE
Add wildcard branch names

### ISSUE THREAD

**Issue by faceleg** [lambci/lambci#25]
I would find it useful to be able to specify branch names with a wildcard, e.g.

```JSON
{
  "feature/*": true
}
```

So I can pipe all `feature/*` noise into a different slack channel.

**Comment by mhart** [comment]
Oh, I totally forgot I had added this – you can already do it! I just forgot to document it.

You can use regex notation and you can also inverse match, like so:

```
`/^dev-/`: true
'!/^test-/': true
```

See the tests for more on this until I document it better: https://github.com/lambci/lambci/blob/master/test/config.js#L52-L104

**Comment by faceleg** [comment]
💃
