### ISSUE TITLE
failed to run phantomjs

### ISSUE THREAD

**Issue by lielran** [lambci/lambci#31]
does lambci currently support PhantomJs? 

I'm using version V0.9.4
this is the error in the report:

```
> phantomjs@1.9.18 install /tmp/lambci/build/MyCompany/myProject/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Received 12854K total.
Extracting tar contents (via spawned process)
Removing /tmp/lambci/build/MyCompany/myProject/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1468393502619/phantomjs-1.9.8-linux-x86_64 -> /tmp/lambci/build/MyCompany/myProject/node_modules/phantomjs/lib/phantom
Phantom installation failed { [Error: ENOSPC: no space left on device, write] errno: -28, code: 'ENOSPC', syscall: 'write' } Error: ENOSPC: no space left on device, write
    at Error (native)
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/brace-expansion/1.1.5/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/log4js/0.6.37/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/lodash/3.10.1/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/ws/1.0.1/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/babel-runtime/6.9.2/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/datejs/0.0.2/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/negotiator/0.4.9/package.tgz
..
..
..
```

**Comment by mhart** [comment]
Last time I checked using https://github.com/Medium/phantomjs it was fine – have you tried that?

**Comment by lielran** [comment]
I give it a try, 
still getting all this untar errors 
```
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/babel-runtime/6.9.2/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/lodash/3.10.1/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/lodash/3.10.1/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/babel-runtime/6.9.2/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/caniuse-db/1.0.30000506/package.tgz
npm ERR! Linux 4.1.19-24.31.amzn1.x86_64
npm ERR! argv "/usr/local/lib64/node-v4.3.x/bin/node" "/var/task/node_modules/.bin/npm" "install"
npm ERR! node v4.3.2
npm ERR! npm  v2.15.9
npm ERR! code ENOSPC
npm ERR! errno -28
npm ERR! syscall write

npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/babel-runtime/6.9.2/package.tgz
npm ERR! tar.unpack untar error /tmp/lambci/home/.npm/lodash/3.10.1/package.tgz
```

**Comment by mhart** [comment]
Oh, well the error says there's no space left on the device – I don't think that's related to phantomjs – that probably just means that you've got more than 500MB of dependencies?

**Comment by lielran** [comment]
```
$ du -sh  node_modules 
658M	node_modules
```
😱

**Comment by mhart** [comment]
Ouch!

Just confirming that phantomjs works:

https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/121/56b350df42bdff3e49d1a691994a148b.html

Going to close this as it's not a problem with phantomjs

**Comment by lielran** [comment]
there isn't workaround for that scenario?
i know that lambda have a limit of 500mb (/tmp) and also I'm not sure aws will support increasing the disk space. also you can't really apply request for increase from the console.

**Comment by mhart** [comment]
As you say, Lambda is limited to 500MB, so unless you can only install the dependencies you need (do you really need that much all at once? can you install some dependencies, then test with them, then remove them, then install other dependencies, etc?) – then the workaround is the same for the other Lambda limitations – to use ECS: https://github.com/lambci/lambci#extending-with-ecs

**Comment by mhart** [comment]
See if you can find which modules are the worst offenders – `du -k | sort -n` or similar – they may have a lot of unnecessary sub-dependencies that you can delete (or test directories, examples directories, documentation, etc)

**Comment by lielran** [comment]
I think i found another way 
```
npm install --production
```
```
$ du -sh  node_modules
120M	node_modules
```

**Comment by mhart** [comment]
Hmmm, but that won't install any of you devDependencies – which you need to run your tests, no?
