### ISSUE TITLE
Add Scala support

### ISSUE THREAD

**Issue by hayd** [lambci/lambci#33]
Considering #14, I wondered if this might be possible!

**Comment by mhart** [comment]
Can you clarify what you mean by Scala support? Scala runs on the JVM, so it should already be supported?

**Comment by lielran** [comment]
I think that the missing part is the installation of sbt. 
unlike Gradle that come out-of-the-box with a wrapper ("gradlew") most scala projects are using SBT. 
beside of that it's the same as java(including run time) 
IMO - simple script will do the trick:

1. just download it from here  http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html 
2. unzip 
3. compile/test/other task

**Comment by mhart** [comment]
Right, that's what I meant with already supported – you can just download `sbt-launch.jar` and run it with Java as-is.

I might consider adding a bootstrapping script in the future to make it a little easier (so I'll keep this issue open), but it should be pretty straightforward to run Scala on LambCI right now.

**Comment by ogrodnek** [comment]
If someone else needs it, here's a [gist of how I'm bootstrapping sbt for lamb](https://gist.github.com/ogrodnek/374063c97f44d2970e84b29357d61b63).

Thanks, mhart, for the great work w/ lamb!
