### ISSUE TITLE
Security implications of publishing build report 

### ISSUE THREAD

**Issue by faceleg** [lambci/lambci#35]
The https://github.com/lambci/lambci#security section is very helpful.

I wonder if it would be even more helpful if the implications of publishing private repo build logs was added?

**Comment by mhart** [comment]
I don't know what you mean – can you be more specific? I already talk about this:

> HTML build logs are generated with random filenames, but are accessible to anyone who has the link. Set s3PublicSecretNames to false to make build logs completely private (you'll need to use the AWS console to access them), or you can remove s3Bucket entirely – you can still see the build logs in the Lambda function output in CloudWatch Logs.

**Comment by faceleg** [comment]
Shouldn't open issues when tired.
