### ISSUE TITLE
Slack message title should contain repo name

### ISSUE THREAD

**Issue by faceleg** [lambci/lambci#36]
This would make it easier to see which repo is building/passing/failing when glancing at slack notifications on mobile devices.

Something like:

`Build #x (started|passed|failed) on user/repository`

**Comment by mhart** [comment]
Yeah, not going to do this for now – it seems like a very specific use case and I don't want to clutter up the title any further at the moment (considering it adds the build time in the title too)

**Comment by faceleg** [comment]
I've been using this for awhile now, and I still really do think this is an easy way to get a usability win in terms of increasing the "at a glance" information available in slack notifications.

I've attached a screen showing what I mean. The screen shows recent notifications for builds completed or failed across 3 different repositories. Notice how it is not possible (at all!) to determine **which** repository has failed to build from the notifications. Notice also the CircleCi Slack notification. Yes it's cluttered, I don't think it is an issue as at least it gives me actionable information without requiring that I click it and open slack. 

![screen shot 2016-08-17 at 9 05 11 pm](https://cloud.githubusercontent.com/assets/1000759/17730741/53c758f4-64be-11e6-97c9-ff0cbd9d0761.jpeg)

**Comment by mhart** [comment]
Ok ok – I've found a way to do this and make us both happy 😸 

Slack has a (badly documented) way of specifying a different title that you see in the notification (using a property called `fallback`) than what you see in the actual message in the channel (which was my main concern)

I'll be pushing out an update with this feature added soon!

**Comment by mhart** [comment]
Updated this in v0.9.7 as well as the latest `lambci/ecs` image

**Comment by faceleg** [comment]
Holy crap thank you!

**Comment by mhart** [comment]
No wuckas bro – lemme know if it works as you expect
