### ISSUE TITLE
Zip Inside of Lambda

### ISSUE THREAD

**Issue by harakiro** [lambci/lambci#41]
I'm trying to figure out how you execute the zip command inside of lambda. It seems that zip is not found in my lambda environment, I don't see it packaged with lambCI anywhere. I've tried executing yum to install it but this requires root access, and sudo isn't present.

I'm trying to have lambCI deploy a lambda function. Since lambCI eats it's own dogfood I'm thinking you've had to solved this.

TIA
Jesse

**Comment by mhart** [comment]
Well, LambCI doesn't *deploy* from LambCI – it eats its own dogfood by running its unit tests in LambCI whenever a push or pull request is triggered.

That said, you *can* use something like https://github.com/lambci/docker-lambda to run `zip` in a Lambda-like environment. LambCI uses this for integration testing.

The `lambci/lambda:build` image comes with all the packages that exist on Lambda, as well as `zip`, `aws-cli`, `git`, `gcc`, etc. So you can install, compile and test your Lambda, and then zip and deploy it from within the docker container.

You can run:

```
docker run -it lambci/lambda:build bash
```

To explore this environment.

**Comment by mhart** [comment]
Btw – to actually get deploys happening *from* LambCI – the best way would be to write the deploy script using Node.js – that way you don't need the `zip` binary

**Comment by mhart** [comment]
The https://github.com/stuk/jszip package should be able to do what you need – but there are others as well, like https://github.com/archiverjs/node-archiver

**Comment by harakiro** [comment]
Thanks so much for the quick response! I'll explore these solutions. I'm also toying with packaging zip up much like you have for gcc etc.

**Comment by mhart** [comment]
Yep, that's certainly another option 👍  – I'm hoping to have time one day to put together a repository of packages that can just be downloaded straight to Lambda, for commonly used commands like git and zip... hopefully will have the time soon! #13

**Comment by harakiro** [comment]
Just wanted to follow up on a couple things in your comments. First things so much for your quick responses. Second, I have success. I now have lambci building and deploying my lambda functions. yay!

Some things I ran across.
1. awscli doesn't seem to exist in the nodejs lambda env.
2. zip does not exist in this environment, but unzip does.
3. installing awscli via pip fails due to read only file system errors.

I've created init scripts for both awscli to install via bundle and zip. The zip install has a dependency on gcc, but everything is working and now builds in about 48s.

If you have any tricks about how to get awscli to install via pip, or if it already exists and I'm looking in wrong place please let me know!

Thanks!

**Comment by mhart** [comment]
Try `pip install --user awscli` – this should work on LambCI

Again, it would require a lot less to be installed if you just did all this in Node.js or Python – they have support for zip and the AWS SDK is installed for both languages... but, up to you.

**Comment by harakiro** [comment]
awesome i'll give this a try as well. I'm not adverse to doing it in node or python, I was trying to take the most generic approach initially (bash) and go from there.
