### ISSUE TITLE
Got ECONNRESET error code for all tests

### ISSUE THREAD

**Issue by danielsukmana** [lambci/lambci#42]
Hello, I'm trying to use LambCI for node project. I've followed the 3-step installation instruction and managed to get the CI working. The problem is that **all** tests failed with `ECONNRESET` error code after ~3:30 build time. If it's indeed a connection problem, I think there should be at least one successful build but I got none. I did some digging found a solution: upgrade node. But that's not possible on AWS (or is it? I'm new in this kind of thing, but I read that AWS lambda only supports node v0.10.36 and v4.3.2; node v4.4 supposedly fix this issue).

Are there any other solution to this? I'm using AWS us-west-2 region and LambCI version 0.9.6.

**Comment by mhart** [comment]
You can use other versions of Node.js no problem – see here for more details: https://github.com/lambci/lambci#nodejs

**Comment by danielsukmana** [comment]
Oh wow, I didn't catch that. It got rid of my `ECONNRESET` problem. Thank you for answering (this silly question)! Also, thank you for creating LambCI. 👍
