### ISSUE TITLE
Old configuration is being used after update

### ISSUE THREAD

**Issue by martinssipenko** [lambci/lambci#44]
There are cases when after pushing a configuration update in `.lambci.json` section, the previous configuration values are being used, given that repository has been pushed and built before.

In case we re-upload the lambda function zip file, the new  configuration is picked up.

Perhaps it has something to do with Lambda container reuse?

Have you ever experienced similar issues?

I'm happy to provide more information to help debug this behaviour.

**Comment by mhart** [comment]
@martinssipenko no I haven't seen this actually – and by default everything in `/tmp` is removed before cloning the git repo, so it would seem a little weird at first glance if this was happening.

Is this for a public or private repo? On a push, or a pull request? Thanks!

**Comment by martinssipenko** [comment]
@mhart I've also noticed that after a while the new config is being picked up (most likely when container times out).

I'm using a private repo and tested with both push and pull request.

The code that is pulled into `/tmp` on subsequent run has the code (config) changes. I think it's simply not being reloaded, because of container reuse.

I'm currently trying to figure out what could be the cause, or how to force reload configuration on each run, but given I'm not node.js expert and not very familiar with codebase it might take some time.

Perhaps you will find following links useful:
https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/
https://www.linkedin.com/pulse/aws-lambda-container-lifetime-config-refresh-frederik-willaert

**Comment by martinssipenko** [comment]
it could be that `var config = require('./utils/config')` in `index.js` is outside of `exports.handler` thus making it "global" for container

**Comment by mhart** [comment]
@martinssipenko that's code though – are you saying you're changing values in code? I thought you said it was your json file settings?

**Comment by mhart** [comment]
@martinssipenko I'm not quite sure what you mean it's "it's simply not reloaded". What is not reloaded? `/tmp` is deleted each time with an `rm` command by default – there can't be anything in `/tmp` after that. Then the repo is checked out in a subdirectory of `/tmp`

There are a number of settings in LambCI to take advantage of container reuse, for caching, etc – but by default these are turned off.

**Comment by martinssipenko** [comment]
@mhart sorry for misunderstanding.

Yes, I am changing json setting. After pushing the changed files, old config is being picked up. Infact, i noticed that if you update config several times, and do it in a small timeframe, the build will pick old config randomly.

I don't think this has anything to do with `/tmp`. As far as I understand, my code is being pulled into `/tmp` on each build, and json file is being read for configuration. I did check and can confirm, that each push with updates in json settings has the changes after git pull, but the config is old (not picked from json).

The code i mentioned above is my first guess to why it might be happening. I think that since `./utils/config` is being loaded outside of `exports.handler` function it gets reused when new job hits an existing container.

**Comment by mhart** [comment]
@martinssipenko the line you're referring to is code – `./utils/config` is a collection of functions – the only thing that could be "cached" is the default base config, and there shouldn't be a problem with that (unless there's a bug)

You can see that a new config is calculated and attached to each build after cloning here: https://github.com/lambci/lambci/blob/master/actions/build.js#L56

So, in any case, let's not assume it's a container reuse issue just yet.

What config settings is it that you're changing and not seeing? And you mentioned that you can definitely get it to happen only on pushes and not just pull requests? I say this because the config is handled differently for each one – by default not every config is inherited for pull requests because of security concerns: https://github.com/lambci/lambci#security

**Comment by martinssipenko** [comment]
@mhart Perhaps we can get in touch in slack/skype or any IM?

**Comment by mhart** [comment]
@martinssipenko sure! https://gitter.im/lambci/lambci

**Comment by mhart** [comment]
For all those following at home, it was indeed a caching issue – `require()` was being used to resolve file config (for `.lambci.js` cases, but also used for `.lambci.json`) – so we have to clear the correct `require.cache` entry each time.

This should be fixed in v0.9.7
