### ISSUE TITLE
PHP Fatal error:  Allowed memory size of X bytes exhausted

### ISSUE THREAD

**Issue by Jonnx** [lambci/lambci#45]
running the default php command (version 5.6.25) the laravel phpunit test runner will not even begin to run the tests as memory is exhausted in the composer post install commands. Anyone run into this issue before and know how to resolve it?

Also: anyone know how to parallelize the builds, i would like to run every single test class in tis own test runnder immediately to avoid memory leak issues and take our test runner for 20 minutes to under 1 minute

here is my .lambci.json (nothing crazy)
```
{
  "cmd": ". ~/init/php 5.6.25 && composer install -n --prefer-dist && vendor/bin/phpunit"
}
```

**Comment by mhart** [comment]
@Jonnx are you running a standard LambCI setup? If so, you'd be on the max Lambda memory setting which is 1.5GB

I haven't run into any problems building Laravel itself, see here for an example: https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/152/8e5c0245bf1a6275ab8394201adec811.html

**Comment by Jonnx** [comment]
yea we have had this same problem on circle ci. really strange we must be doing something wrong. we built a custom test runner script to deal with that issue but its never come up in the composer post update / install steps before.

**Comment by mhart** [comment]
Is something doing an `ini_set` somewhere to restrict it?

I wonder if adding `ini_set('memory_limit', -1);` to the failing script would work?

**Comment by Jonnx** [comment]
figured out how to solve the issue.
1) removed the composer post updated / install command entries
2) ran the php artisan optimize in the runner script instead of the composer.json
3) upped the phpunit memory limit to 2gb with the -d switch

```
{
  "cmd": ". ~/init/php 5.6.25  && composer install --dev && composer dumpautoload && php artisan optimize && php artisan route:scan && vendor/bin/phpunit -d memory_limit=2048M"
}
```

**Comment by Jonnx** [comment]
reopened by mistake, sorry

**Comment by mhart** [comment]
All good, glad you got it working! 👍
