### ISSUE TITLE
Coverage Reports on Specific Branches

### ISSUE THREAD

**Issue by Jonnx** [lambci/lambci#46]
is it possible to compile coverage reports and store them for later access when tests are being run on a specific branch?

**Comment by mhart** [comment]
@Jonnx there's nothing specific for this – you can store any build artifacts you want manually by uploading them to S3 (the AWS credentials should be available as env vars, assuming you're not doing public builds)

**Comment by Jonnx** [comment]
we are not doing public builds.so providing the bucket param int he config will just push all artifacts up to s3? any reason they are not included in the s3 folders where the run reports are being stored?

**Comment by mhart** [comment]
@Jonnx Not sure what you mean by "they"? The only thing uploaded to S3 automatically is the build log. If you want to upload anything else, you can, but you'll need to do it manually

**Comment by Jonnx** [comment]
@mhart by "they" i meant the build artifacts. does doing it manually mean just providing the s3 bucket name or doe we need to write a custom script for that?

**Comment by mhart** [comment]
Well LambCI doesn't know what your build artifacts are. You'll need to provide a custom script if you want to upload anything – Node.js or Python would be easiest considering they already have the AWS libs installed for them.

**Comment by Jonnx** [comment]
sounds good we will take a look at writing our own script for that once we get the tests to run. thanks for the info.

**Comment by dej611** [comment]
While uploading the file with a custom scripts it's feasible it would be nice to customize the HTML report that LambCI generates. Perhaps letting the user to add a link to another local HTML page (i.e. the coverage report).
I'm saying this as some users won't notice the coverage unless reported/mentioned in the LambCI report.

**Comment by mhart** [comment]
@dej611 anything that looks like a link in the log will be turned into a clickable link in the HTML report – so you can log `http://whatever.com/my/coverage/report` to stdout in your case.

If you want to customize the HTML for your LambCI setup, the template is here: https://github.com/lambci/lambci/blob/master/html/build.html.js

**Comment by dej611** [comment]
Great, I didn't know of the `stout` trick.

On editing the template, I thought about that but it would be nice if we can do that somewhere in the configuration.

**Comment by mhart** [comment]
Closing as this isn't something we're likely to support specifically, beyond what's available now
