### ISSUE TITLE
It would be nice to have also the PR title in the Slack notification

### ISSUE THREAD

**Issue by dej611** [lambci/lambci#56]
This is an enhancement to the current state.

Nothing super serious, but it would be nice to have also the title of the PR, next to the ID - and perhaps a way to toggle this via configuration.

Thanks for your awesome tool!

**Comment by mhart** [comment]
I thought about it originally, but it clutters things too much – especially for most PR titles that would need to be truncated.

I'm going to close this for now (my aim is to keep the number of config options to a complete minimum) – but if there's enough additional support from the rest of the users I'm happy to revisit.
