### ISSUE TITLE
LambCI badge URL missing

### ISSUE THREAD

**Issue by dej611** [lambci/lambci#57]
I've tried to follow the guide on how to add the lambci badge for the build but I think I missed some steps.

I see in the `readme.md` the following URLs:

```
Branch log: https://<bucket>/<project>/branches/master/<somehash>.html
Branch status img: https://<bucket>/<project>/branches/master/<somehash>.svg
```

But In my log I've got only the `Branch Log` with no `Branch status img` line.

Looking into S3 I do not find the `svg` file: does it mean I have to programmatically copy the SVG file in my build script? Or maybe there's an option I missed to enable it?

**Comment by mhart** [comment]
@dej611 are you looking at a branch build or a pull request build? The URL only shows up on branch builds (doesn't typically make sense to have a badge for a PR)

If you push to master, the URL should show up there

**Comment by dej611** [comment]
My bad, I made confusion as our main branch has a different name from `master`, therefore I thought for some strange reason to look at the `builds` folder.

I think you can close this one now. Thanks.

**Comment by mhart** [comment]
By all means – if it's resolved you can close it! 👍
