### ISSUE TITLE
building dotnet code - will not work 

### ISSUE THREAD

**Issue by perryofpeek** [lambci/lambci#59]
Hi, 
spent some time trying to get dotnet (core) code to build using lambda only. 
this will not work , due to disk space issues , 512MB is not enough space for dotnet to do a "restore" 
just wanted to let people know. 

here is an example script if you want to try it. 
echo "###1"
df -h
export LD_LIBRARY_PATH=$(pwd)/shared/Microsoft.NETCore.App/1.0.1/
curl -sSL https://s3-eu-west-1.amazonaws.com/public-s3-hailbus-com/dotnet_libs.tar.gz -o dotnet_libs.tar.gz
tar -zxf dotnet_libs.tar.gz
rm -f dotnet_libs.tar.gz
curl -sSL https://s3-eu-west-1.amazonaws.com/public-s3-hailbus-com/dotnet.tar.gz -o dotnet.tar.gz 
tar -zxf dotnet.tar.gz
echo "###2"
df -h
rm -f ./dotnet.tar.gz
echo "###3"
df -h 
ls -al
mv lib* shared/Microsoft.NETCore.App/1.0.1/
./dotnet --version
./dotnet restore --packages packages
./dotnet build

Here is the output 
./dotnet restore --packages packages
Expanding 0%Expanding 1%Expanding 2%Expanding 3%Expanding 4%Expanding 5%Expanding 6%Expanding 7%Expanding 8%Expanding 9%Expanding 10%Expanding 11%Expanding 12%Expanding 13%Expanding 14%Expanding 15%Expanding 16%Expanding 17%Expanding 18%Expanding 19%Expanding 20%Expanding 21%Expanding 22%Expanding 23%Expanding 24%Expanding 25%Expanding 26%Expanding 27%Expanding 28%Expanding 29%Expanding 30%Expanding 31%Expanding 32%Expanding 33%Expanding 34%Expanding 35%Expanding 36%Expanding 37%Expanding 38%Expanding 39%Expanding 40%Expanding 41%Expanding 42%Expanding 43%Expanding 44%Expanding 45%Expanding 46%Expanding 47%Expanding 48%Expanding 49%Expanding 50%Expanding 51%Expanding 52%Expanding 53%Expanding 54%Expanding 55%Expanding 56%Expanding 57%Expanding 58%Expanding 59%Expanding 60%Expanding 61%Expanding 62%Expanding 63%Expanding 64%Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       30G  3.3G   27G  11% /
/dev/loop0      526M  515M     0 100% /tmp
total 188

**Comment by perryofpeek** [comment]
for information only.

**Comment by mhart** [comment]
Thanks @perryofpeek! What's the ultimate size if you prebuild it on another machine (eg, an Amazon Linux AMI)? Just wondering if it would still be possible to use after compilation.

**Comment by owain-perry** [comment]
I will check this out for you. when I get a moment next week.
