### ISSUE TITLE
deploying another aws service (s3/lambda/cloudformation)

### ISSUE THREAD

**Issue by thewillhuang** [lambci/lambci#65]
I've been trying hard to deploy an [Apex](http://apex.run/) lambda function via LambCi to get the same build environment. I'm having some difficulty.

In my dynamo DB, I've set up a separate AWS credential and region just like the readme. But I get an error similar to https://gist.github.com/cmawhorter/3cf67164414c4a97fcd8

I've also tried every step given in the gist that includes
- lambda full access permission
- IAM roles full permission

My suspicion is that somehow the AWS credentials that I gave it is being replaced by lambda's own credentials.

I've also tried to get Apex to run on and it was successful. The commands and the AWS credentials are the same.

so my question is, what's the best way to **securely** use another AWS credential in a public repo? Or better yet, what am I doing wrong and how to fix it?

**Comment by mhart** [comment]
@thewillhuang the best way would be to give the Lambda function (LambCI's Lambda function) the correct permissions – so modify LambCI's IAM role accordingly. That way you're not passing credentials around.

Lambda populates the `process.env.AWS_*` variables every invocation with its temporary credentials, so I'm guessing that's why everything you're trying isn't working. You'd have to override those variables in your function body with your own values (or construct the `AWS` sdk objects with your own values, not ones from `process.env.AWS_*`) if you wanted to do it without modifying LambCI's IAM.

**Comment by thewillhuang** [comment]
Excellent! I got it to work, thank you so much!

Would you ever consider a feature to inject a separate AWS cred then revert to lambCI's lambda AWS credentials after some process? Is that a possibility for lambda's architecture?

I believe there can be a lot of use cases that would prove beneficial. For example, uploading built assets to S3 etc. Would you accept a PR to make such a use case possible?

**Comment by mhart** [comment]
@thewillhuang well `secretEnv` can be used for this very purpose – just define variables using different names than the ones Lambda will override and then use them to create your AWS objects.

This use case is possible already and very straightforward – I don't think I'd want to add anything else here. What are you suggesting?

**Comment by mhart** [comment]
(also, I still believe that modifying LambCI's IAM Role is the most secure way to achieve this, rather than passing around secret keys)

**Comment by thewillhuang** [comment]
Makes sense! The main problem is that sometimes with other libraries such as Apex, it is not possible to call another ENV unless I fork it and rebuild it from source. Depending on the author of these tools, it's not always something the user has control over. Which is why I think having a way to set a new AWS credential by default and revert to lambda's would be a better developer experience

**Comment by mhart** [comment]
> would be a better developer experience

Well, I respectfully disagree – everyone I know managing other AWS assets from LambCI is using the IAM role for this. I'm not sure how it's a better experience to have to create a whole new set of credentials and define them as variables, instead of just adding capabilities to the existing role without any code at all?

I'm still not entirely sure what you're suggesting here btw – doesn't `secretEnv` already cover your situation?

**Comment by thewillhuang** [comment]
You are correct. `secretEnv` does cover my use case as long as it is not `AWS_ACCESS_KEY_ID` `AWS_SECRET_ACCESS_KEY`. The main problem is I did set a new AWS credential using `secretEnv` by editing dynamo DB's table, However, it is being replaced by lambci's AWS credentials.

The `ENV` being replaced is the part that I don't expect should happen for a CI and it is also the sole reason why I think the developer experience could be better.

Does that clear it up?

**Comment by mhart** [comment]
@thewillhuang right, but I'm just not sure what you're proposing as a PR? It's Lambda itself that sets those variables (not LambCI) - although of course LambCI relies on them implicitly when communicating with DynamoDB and S3.

**Comment by thewillhuang** [comment]
Went looking through the code, I get your point now. DynamoDB, S3 are using the AWS credentials implicitly.
I guess if a PR were to be made, I'd export the current lambda injected credentials, under `LAMBCI_ AWS_ACCESS_KEY_ID` and `LAMBCI_ AWS_SECRET_ACCESS_KEY` inject explicitly lambda credentials to DynamoDB and S3 on their initialization so they are not using the globals. Finally, override the global credentials with `secretEnv`, but this time, secretEnv could contain another AWS credential

**Comment by joekiller** [comment]
Looking at your code, I wouldn't pass credentials to my Client function (see [Line 43](https://gist.github.com/cmawhorter/3cf67164414c4a97fcd8/revisions#diff-73654fb858684160f86a6b76afb2a6fdR43)) and would instead rely on the intrinsic AWS.CredentialProviderChain which will discover the IAM role permissions you have given the to Lambda function and assume them as needed. 

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html

**Comment by thewillhuang** [comment]
yeah http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html just found this, looks like bad practice to do so. thanks!

**Comment by joekiller** [comment]
@thewillhaung check out http://docs.aws.amazon.com/lambda/latest/dg/intro-permission-model.html#lambda-intro-execution-role if you haven't found that part.
