### ISSUE TITLE
Docker inside?

### ISSUE THREAD

**Issue by deitch** [lambci/lambci#67]
I have to say (again), this is fantastic. I would love to use this as my primary CI/CD.

The only challenge is that I have containers everywhere. Because I want dev/staging/prod parity, I do all of my builds and tests inside docker. Essentially, my Makefile looks like this (e.g. for a node app, simplified):

```make
build:
   docker build -t $(IMAGE_NAME):$(BUILD_VER) .

test: build
   docker run --rm $(IMAGE_NAME):$(BUILD_VER) npm test

deploy:
   docker push $(IMAGE_NAME):$(BUILD_VER)
```

I get it, it is a limitation of lambda that you cannot run docker inside lambda. And, yes, I saw the ECS integration. But still would be really great.

**Comment by mhart** [comment]
@deitch if it's a limitation of Lambda, it's a limitation of LambCI – the ECS integration is exactly what you want here

**Comment by deitch** [comment]
>  it's a limitation of Lambda, it's a limitation of LambCI

Yeah, I know. I was kind of hoping it would lead to some cool new way to make it happen. I guess not. Lambda just isn't built for that, is it?
