### ISSUE TITLE
Deployment of Lambda function

### ISSUE THREAD

**Issue by davesade** [lambci/lambci#75]
Hello!
I read the documentation, I see that LambCI does support NodeJS, but I couldn't figure out with certainity, if I can use LambCI to deploy my own Lambda functions.
I have used very simple deployment before, but that required public repos to be used. I do like OAuth with LambCI.
Thanks for the response.

**Comment by mhart** [comment]
@davesade you sure can!

You can use `python -m zipfile -c <file․zip> <files>` in your LambCI script to create your zip file (or use a package like [JSZip](https://github.com/stuk/jszip) if you prefer), and then write a script using the AWS-SDK to deploy your Lambda function (you can control access via the LambCI function IAM role)

The functions you'll probably use the most are [createFunction](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property) and/or [updateFunctionCode](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#updateFunctionCode-property)
