### ISSUE TITLE
Password protected public Build  logs with AES using CryptoJS 

### ISSUE THREAD

**Issue by Tanmayshetty** [lambci/lambci#80]
Hi,
It would be great to have a password protected build logs with the implementation similar to [staticcrypt](https://robinmoisson.github.io/staticrypt/).

 [Example](https://robinmoisson.github.io/staticrypt/example.html)

The password for encryption should  be set in the config files.

Thanks

**Comment by mhart** [comment]
I don't think I'll add this – future version of LambCI should have a better way of doing this – but thanks for the suggestion!
