### ISSUE TITLE
Fails when overlay2 is used

### ISSUE THREAD

**Issue by cscetbon** [lambci/lambci#81]
Rpm doesn't play well with overlay2 and because of it yum-plugin-ovl should be installed to avoid issues. see example at https://pastebin.com/Va7XbHER

**Comment by mhart** [comment]
I think you've got the wrong repo – you want https://github.com/lambci/docker-lambda

In any case – rpm isn't something that you can use on Lambda, so I'm not sure this is a problem?

**Comment by cscetbon** [comment]
This is a problem when you want to compile python packages and you need to install yum packages (rpm) to do it

**Comment by mhart** [comment]
Hmmm, so if you're using overlay2, can't you install `yum-plugin-ovl`? I'm just not sure it should be the responsibility of docker containers to account for which filesystem they might be run on – although if many ppl are running overlayfs, I can see how this would be convenient

**Comment by cscetbon** [comment]
Overlay2 is the default on macOS and I'm sure on many others too as it's supposed to be more efficient than aufs. It's also annoying
