### ISSUE TITLE
Including yarn

### ISSUE THREAD

**Issue by nguyenchr** [lambci/lambci#82]
I saw that you mentioned you were thinking of including in yarn in https://github.com/lambci/lambci/issues/71

Just wondering if there has been anymore thought into this?
It would be useful for my particular use case at the moment

**Comment by mhart** [comment]
Yep – still on the cards. A decent workaround is just downloading it as the first step in your build.

**Comment by nguyenchr** [comment]
yeah I was thinking that, but my builds are already approaching 5m as it is, for now I'm just using the npm equivalent commands so everything is working dandy 👍

**Comment by mhart** [comment]
Oh, the downloading would add only literally a couple of seconds to your build – network speed is fast from Lambda – so I wouldn't worry about that aspect.

**Comment by mhart** [comment]
Going to close this – I think just installing this in your build is the best bet – yarn actually [has some issues with disk usage](https://github.com/yarnpkg/yarn/issues/986) that's made me avoid it on Lambda anyway.

**Comment by ajhool** [comment]
I've had trouble downloading yarn as my first build step using these commands;

```
FROM lambci/lambda:build-nodejs10.x

ENV AWS_DEFAULT_REGION us-east-1

RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo |  tee /etc/yum.repos.d/yarn.repo
RUN yum install yarn

COPY . .
```

Is there a working example that could help guide me?

**Comment by j0k3r** [comment]
Use that in a `.sh` script:

```sh
# manual install yarn
curl -o- -L https://yarnpkg.com/install.sh | bash

# enable yarn in cli
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

yarn install
```
