### ISSUE TITLE
s3PublicSecretNames behaviour on public repos

### ISSUE THREAD

**Issue by franciscocpg** [lambci/lambci#84]
I was doing some tests with a public repo and have tried the `s3PublicSecretNames` options but it wasn't working as expected (that is, as described here https://github.com/lambci/lambci#security my build logs weren't private at all).

After inspecting the code (see snippet below) I realized that this options only works if the repo is private but I think that's not clear in the README security section.

May I propose a PR to let this information clearer in the README?

https://github.com/lambci/lambci/blob/e643500706258ee3f49779d0de27da7841511bc6/utils/log.js#L84-L93

**Comment by mhart** [comment]
Ah you had a public repo – I see what you mean. Yeah, the instructions assume you're trying to protect the logs of a private repo.

Happy for you to come up with some clarifying documentation if you'd like!
