### ISSUE TITLE
build args

### ISSUE THREAD

**Issue by slajax** [lambci/lambci#88]
Currently build args are passed like so:
`docker build --build-args 'X=Y'` 

It would be nice if they were passed as:
`docker build --build-args "X=Y"`

This would allow us to do:
`docker build --build-args "NPM_TOKEN=${NPM_TOKEN}"`

rather then:
`docker build --build-args 'NPM_TOKEN=000-000-000-000'`

... which means tokens are hardcoded rather injected at build-time, which is the point of build args.

As far as I can tell, the only change required is to make sure the docker build command wraps build args in double quotes instead of single quotes [here](https://github.com/lambci/ecs/blob/master/runbuild.sh#L10) or [here](https://github.com/lambci/lambci/blob/master/actions/build.js#L309):

```
❯ export NPM_TOKEN=test
❯ echo '$NPM_TOKEN'  
$NPM_TOKEN
❯ echo "$NPM_TOKEN"
test
```

Happy to implement it in the code, if you can tell me what the best way for testing / releasing it is.

**Comment by mhart** [comment]
I assume you're talking about the ECS integration? Have you tried using `secretEnv` properties for this? https://github.com/lambci/lambci#overriding-default-properties

**Comment by slajax** [comment]
Yes, I am. 

I tried this, and it doesn't work because the build args are wrapped in single quotes when ran so env vars aren't expanded. That said if I hardcode my npm token into the build args config, it does works fine. I'd like to be able to use the env var from secretEnv inside  build args. To do that, it has to be wrapped in double quotes or not at all. Single quotes casts the entire build build arg to string. I'll try to post a better example soon.

**Comment by slajax** [comment]
To be clear, at the end of the day, I would like to be able to do this:

```
docker: {
  buildArgs: "--build-args NPM_TOKEN=${NPM_TOKEN}"
}
```
but I can't today because `${NPM_TOKEN}` isn't expanded, because it is encapsulated in single quotes rather then double quotes when it is run on the command line in test runner.

**Comment by mhart** [comment]
`--build-arg NPM_TOKEN` should work just fine?

**Comment by slajax** [comment]
Oh interesting. So you mean if I omit the value, docker will automatically infer the arg value from env vars? I'll try that, thanks!

Didn't know docker would do that, or is that part of filterEnv?

**Comment by mhart** [comment]
That's just Docker – it's the same with the `-e` argument to `docker run`

This works fine for me:

```Dockerfile
FROM alpine

ARG NPM_TOKEN

RUN echo $NPM_TOKEN
```

```console
$ NPM_TOKEN=thing docker build --no-cache --build-arg NPM_TOKEN .
Step 1/3 : FROM alpine
 ---> a41a7446062d
Step 2/3 : ARG NPM_TOKEN
 ---> Running in cc6682dbef6a
 ---> 3a13dfb5ed39
Removing intermediate container cc6682dbef6a
Step 3/3 : RUN echo $NPM_TOKEN
 ---> Running in c309ccde6718
thing
 ---> b184dabe19b6
Removing intermediate container c309ccde6718
Successfully built b184dabe19b6
```

**Comment by slajax** [comment]
@mhart awesome, that works, thanks!
