### ISSUE TITLE
Bump git to 2.14.2

### ISSUE THREAD

**Issue by cjs** [lambci/lambci#93]
The shipped git is out of date, and possibly insecure. I'd like to bump the shipped version to 2.14.2. I'll be submitting a PR with that change, but I wanted to check the process to recompile git.

I've performed the following steps:

#### Setup
- Bring up an Amazon Linux instance
-  `sudo yum groupinstall "Development Tools"`
- `sudo yum install git`
- `mkdir ~/install`
- `mkdir ~/discard`

#### openssh

- `git clone https://github.com/openssh/openssh-portable.git`
- Comment `sshconnect.h` per https://github.com/lambci/lambci/issues/26#issuecomment-274876986
- `sudo yum install openssl-devel`
- `sudo yum install perl-devel`
- run `autoreconf`
- `./configure --prefix=$HOME/install --sysconfdir=$HOME/discard --sbindir=$HOME/discard --mandir=$HOME/discard`
- `make`
- `make install`
- cd

#### Git

- `wget https://www.kernel.org/pub/software/scm/git/git-2.14.2.tar.xz`
- `tar xf git-2.14.2.tar.xz`
- `cd git-2.14.2`
- `./configure --prefix=$HOME/install --mandir=$HOME/discard --htmldir=$HOME/discard --infodir=$HOME/discard --without-tcltk`
- `make`
- `make install`

Then , tar up `~/install` and drop it into the `vendor` directory.

Any comments, things I missed, or extra things that should be done?

**Comment by fxfitz** [comment]
(once you figure it out, this might be a cool thing to document or have a script ready to do it for you)

**Comment by fxfitz** [comment]
On a side note... how does one *use* the git tarball on a Lambda instance? Download the tarball, extract, and run? I'm getting a read only filesystem error... :-(

**Comment by cjs** [comment]
You don’t need to do anything. It’s autoexpanded at https://github.com/lambci/lambci/blob/master/utils/config.js#L88 and used in the clone function https://github.com/lambci/lambci/blob/master/actions/build.js#L135

**Comment by fxfitz** [comment]
Sorry, I mean outside of LambCI; I'm attempting to use the git tarball on a vanilla Lambda instance.

**Comment by mhart** [comment]
@fxfitz you can only write to `/tmp`, so you've got to do everything out of there. Aside from that there are a number of env vars you need to ensure are setup. Bit too many to remember off the top of my head, but if you copy all the env vars that LambCI sets, you should be good

**Comment by fxfitz** [comment]
Thanks for the info! I'll give it a shot!

**Comment by WhiteHotLoveTiger** [comment]
Thanks for documenting this @cjs 
Aside from bumping up the git version number, is there anything you'd do differently, or are doing differently these days?
@mhart, I recall reading somewhere that you were able to keep the size of the tarball really small. Did you have a different method than this?

**Comment by cjs** [comment]
@WhiteHotLoveTiger I am still waiting on documentation on how @mhart built his version. The size differential means there's some difference I don't know about and that troubles me.

**Comment by marcelobern** [comment]
@cjs are you still looking into an updated git version?

I am working on an approach for faster load time of [`lambda-git`](https://github.com/pimterry/lambda-git/issues/12) which I believe we will be able to use later on to update the git version.

Just let me know.

BTW, thanks a bunch for documenting this process!

**Comment by cjs** [comment]
Hi @marcelobern I think it would be useful for this project to be able to update the version, so I'm eager to see what you can do.

**Comment by mhart** [comment]
You can get git 2.13.5 in the version-0.10.0 branch: https://github.com/lambci/lambci/tree/version-0.10.0/vendor

**Comment by mhart** [comment]
You can see how I built it here: https://github.com/lambci/lambci/tree/version-0.10.0/build/git

**Comment by marcelobern** [comment]
@mhart thanks for sharing git 2.13.5 and the corresponding instructions!

FYI, I came across a few permission issues by using `git-2.13.5.tar` which were not there in `git-2.4.3.tar`. Not sure if these will lead to any issues for you, so just in case, here they are:
- `bin/git/usr/bin/ssh-agent` - no read/write (o2111), it used to be o711
- `bin/git/usr/libexec/openssh/ssh-keysign` - no read/write (o111), it used to be o711

**Comment by mhart** [comment]
@marcelobern oh thanks for the heads up – I'll double check these and fix if necessary

**Comment by marcelobern** [comment]
@mhart and @cjs with the release of AWS Lambda layers, I just packaged the git version provided as a Lambda layer to avoid uploading all binaries with each new code change.

It is available at npm as [lambda-layer-git](https://www.npmjs.com/package/lambda-layer-git).

I would love to hear any feedback you might have on this being useful to you (and others).

**Comment by cjs** [comment]
I'll defer to @mhart, I haven't even looked at Lambda layers yet.

**Comment by mhart** [comment]
@marcelobern I did the same thing a few weeks ago – with an updated git version: https://github.com/lambci/git-lambda-layer 👍

**Comment by cjs** [comment]
Now that https://github.com/lambci/git-lambda-layer I think this issue can be closed.
